# Site settings
title: NNE
header-img: assets/images/home-bg.jpg
description: "News"
baseurl: "/"
url: "http://blog.nne.vn"
twitter_username: nne_tech
github_username:  nnetech

# Build settings
timezone: Europe/London
markdown: kramdown
highlighter: rouge
permalink: /post/:title
paginate: 5
paginate_path: '/blog/:num'
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

kramdown:
    input: GFM
